=== 模式匹配

Scala has native pattern matching, one of the advantages over __plain__ Java. The basic syntax is close to Java's switch:

Scala 具有原生模式匹配，这是与普通 Java 相比的优势之一。基本语法接近 Java 的 switch：


[source,java]
----
val s = i match {  
  case 1 => "one"
  case 2 => "two"
  case _ => "?"
}
----

Notably __match__ is an expression, it yields a result. Furthermore it offers

值得注意的是 __match__ 是一个表达式，它产生一个结果。 此外，它还提供

*   可命名参数 ``case i: Int => "Int " + i``
*   对象解构 ``case Some(i) => i``
*   guard语句 ``case Some(i) if i > 0 => "positive " + i``
*   多种条件 ``case "-h" | "--help" => displayHelp``
*   编译时检查穷尽性

模式匹配是一个很棒的特性，它使我们免于编写一堆 if-then-else 分支。 它在专注于相关部分的同时减少了代码量。

==== Java Match 的基础知识

Vavr 提供了一个与 Scala 匹配的匹配 API。 通过向我们的应用程序添加以下导入来启用它：

[source,java]
----
import static io.vavr.API.*;
----

拥有静态方法 __Match__、__Case__ 和 __atomic patterns__

*   ``$()`` - 通配符模式
*   ``$(value)`` - 等于模式
*   ``$(predicate)`` - 条件模式

in scope, the initial Scala example can be expressed like this:
在范围内，初始Scala示例可以表示为：

[source,java]
----
String s = Match(i).of(  
    Case($(1), "one"),
    Case($(2), "two"),
    Case($(), "?")
);
----

⚡ 我们使用统一的大写方法名称，因为“case”是 Java 中的一个关键字。 这使得 API 很特别。

===== 穷尽性


最后一个通配符模式 ``$()`` 使我们免于出现 MatchError，如果没有匹配项，则会抛出该错误。

因为我们不能像 Scala 编译器那样执行详尽检查，所以我们提供了返回可选结果的可能性：

[source,java]
----
Option<String> s = Match(i).option(  
    Case($(0), "zero")
);
----

===== 语法糖

如前所述，“Case”允许匹配条件模式。

[source,java]
----
Case($(predicate), ...)
----

Vavr 提供了一组默认 predicate。

[source,java]
----
import static io.vavr.Predicates.*;
----

These can be used to express the initial Scala example as follows:

这些可用于表达初始 Scala 示例，如下所示：

[source,java]
----
String s = Match(i).of(  
    Case($(is(1)), "one"),
    Case($(is(2)), "two"),
    Case($(), "?")
);
----

**多重条件**

我们使用 ``isIn`` predicate 来检查多个条件：

[source,java]
----
Case($(isIn("-h", "--help")), ...)
----

**执行副作用**

Match acts like an expression, it results in a value. In order to perform side-effects we need to use the helper function ``run`` which returns ``Void``:

Match 就像一个表达式，它产生一个值。 为了执行副作用，我们需要使用辅助函数 ``run`` ，它返回 ``Void``：

[source,java]
----
Match(arg).of(  
    Case($(isIn("-h", "--help")), o -> run(this::displayHelp)),
    Case($(isIn("-v", "--version")), o -> run(this::displayVersion)),
    Case($(), o -> run(() -> {
        throw new IllegalArgumentException(arg);
    }))
);
----

⚡ ``run`` 用于解决歧义，因为``void`` 在 Java 中不是有效的返回值。

*警告:* ``run`` 不得用作直接返回值，即在 lambda 主体之外：

[source,java]
----
// Wrong!
Case($(isIn("-h", "--help")), run(this::displayHelp))
----

Otherwise the Cases will be eagerly evaluated __before__ the patterns are matched, which breaks the whole Match expression. Instead we use it within a lambda body:

否则，将在匹配模式之前过早的判断 Cases，这会破坏整个 Match 表达式。 相反，我们在 lambda 体中使用它：

[source,java]
----
// Ok
Case($(isIn("-h", "--help")), o -> run(this::displayHelp))
----

如我们所见，如果使用不当，``run`` 很容易出错。 当心。 我们考虑在未来的版本中弃用它，也许我们还会提供更好的 API 来执行副作用。

===== 命名参数

Vavr 利用 lambda 为匹配值提供命名参数。

[source,java]
----
Number plusOne = Match(obj).of(  
    Case($(instanceOf(Integer.class)), i -> i + 1),
    Case($(instanceOf(Double.class)), d -> d + 1),
    Case($(), o -> { throw new NumberFormatException(); })
);
----

So far we directly matched values using atomic patterns. If an atomic pattern matches, the right type of the matched object is inferred from the context of the pattern.

到目前为止，我们使用原子模式直接匹配值。 如果原子模式匹配，则从模式的上下文中推断出匹配对象的正确类型。

Next, we will take a look at recursive patterns that are able to match object graphs of (theoretically) arbitrary depth.

接下来，我们将看看能够匹配（理论上）任意深度的对象图的递归模式。

===== 对象解构

In Java we use constructors to instantiate classes. We understand __object decomposition__ as destruction of objects into their parts.

在 Java 中，我们使用构造函数来实例化类。 我们将**对象解构**理解为将对象分解为它们的部分。

While a constructor is a __function__ which is __applied__ to arguments and returns a new instance, a deconstructor is a function which takes an instance and returns the parts. We say an object is __unapplied__.

构造函数是应用于参数并返回新实例的函数，而析构函数是接受实例并返回部分的函数。 我们说一个对象没有被应用(__unapplied__)

Object destruction is not necessarily a unique operation. For example, a LocalDate can be decomposed to

对象解构不一定是唯一的操作。 例如，一个 LocalDate 可以分解为

*   年、月和日组件
*   表示对应 Instant 的 epoch millisecond 的 long 值
*   等等。

==== Patterns


在 Vavr 中，我们使用模式来定义如何解构特定类型的实例。 这些模式可以与 Match API 结合使用。

===== Predefined Patterns 预定义模式

For many Vavr types there already exist match patterns. They are imported via

对于许多 Vavr 类型，已经存在匹配模式。 它们是通过导入的

[source,java]
----
import static io.vavr.Patterns.*;
----


例如，我们现在可以匹配 Try 的结果：

[source,java]
----
Match(_try).of(  
    Case($Success($()), value -> ...),
    Case($Failure($()), x -> ...)
);
----

⚡ A first prototype of Vavr's Match API allowed to extract a user-defined selection of objects from a match pattern. Without proper compiler support this isn't practicable because the number of generated methods exploded exponentially. The current API makes the compromise that all patterns are matched but only the root patterns are __decomposed__.

Vavr Match API 的第一个原型允许从匹配模式中提取用户定义的对象选择。 如果没有适当的编译器支持，这是不切实际的，因为生成的方法的数量呈指数级增长。 目前的API做了妥协，所有模式都匹配，但只有根模式被分解

[source,java]
----
Match(_try).of(  
    Case($Success($Tuple2($("a"), $())), tuple2 -> ...),
    Case($Failure($(instanceOf(Error.class))), error -> ...)
);
----

Here the root patterns are Success and Failure. They are decomposed to Tuple2 and Error, having the correct generic types.

这里的根模式是成功和失败。 它们被分解为 Tuple2 和 Error，具有正确的泛型类型。

⚡ Deeply nested types are inferred according to the Match argument and __not__ according to the matched patterns.

⚡ 深度嵌套的类型是根据 Match 参数而**不是**根据匹配的模式来推断的。

===== 用户定义的模式

It is essential to be able to unapply arbitrary objects, including instances of final classes. Vavr does this in a declarative style by providing the compile time annotations ``@Patterns`` and ``@Unapply``.

能够 unapply 应用任意对象至关重要，包括 final 类的实例。 Vavr 通过提供编译时注释``@Patterns`` 和``@Unapply`` 以声明式的方式完成此操作。


要启用注解处理器，需要将 artifact http://search.maven.org/#search%7Cga%7C1%7Cvavr-match[vavr-match] 添加为项目依赖项。


⚡ 注意：当然可以不使用代码生成器直接实现模式。 有关更多信息，请查看生成的源代码。

[source,java]
----
import io.vavr.match.annotation.*;

@Patterns
class My {

    @Unapply
    static <T> Tuple1<T> Optional(java.util.Optional<T> optional) {
        return Tuple.of(optional.orElse(null));
    }
}
----


注解处理器将文件 MyPatterns 放在同一个包中（默认情况下在 target/generated-sources）。 支持内部类。 特殊情况：如果类名是$，生成的类名就是 Patterns，没有前缀。

===== Guards

现在我们可以使用 __guards__ 匹配 Optional 。

[source,java]
----
Match(optional).of(  
    Case($Optional($(v -> v != null)), "defined"),
    Case($Optional($(v -> v == null)), "empty")
);
----

The predicates could be simplified by implementing ``isNull`` and ``isNotNull``.

可以通过实现``isNull``和``isNotNull``来简化 predicate。

⚡ 是的，提取 null 很奇怪。 与其使用 Java 的 Optional，不如试试 Vavr 的 Option！

[source,java]
----
Match(option).of(  
    Case($Some($()), "defined"),
    Case($None(), "empty")
);
----
